import { categories } from "@/config/categories";

export type ToolConfig = {
  slug: string;
  name: string;
  description: string;
  category: (typeof categories)[number]["slug"];
  route: string;
  keywords: string[];
  title: string;
  metaDescription: string;
  featured?: boolean;
  popular?: boolean;
  isNew?: boolean;
  ogImage?: string;
  related?: string[];
};

export const toolsConfig: ToolConfig[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify and validate JSON payloads quickly.",
    category: "developer",
    route: "/tools/json-formatter",
    keywords: ["json", "format", "minify", "validate", "api"],
    title: "JSON Formatter | Altcore Tools Studio",
    metaDescription: "Format, validate and minify JSON instantly in your browser.",
    featured: true,
    popular: true,
    related: ["regex-tester", "base64-encoder-decoder", "url-encoder-decoder"]
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with flags and snippet presets.",
    category: "developer",
    route: "/tools/regex-tester",
    keywords: ["regex", "regexp", "match", "pattern", "flags"],
    title: "Regex Tester | Altcore Tools Studio",
    metaDescription: "Live regex testing with match results and practical snippets.",
    featured: true,
    popular: true,
    related: ["json-formatter", "base64-encoder-decoder", "jwt-decoder-inspector"]
  },
  {
    slug: "json-to-typescript-generator",
    name: "JSON to TypeScript Generator",
    description: "Generate TypeScript interfaces from JSON with nested support.",
    category: "developer",
    route: "/tools/json-to-typescript-generator",
    keywords: ["json", "typescript", "interface", "type generator"],
    title: "JSON to TypeScript Generator | Altcore Tools Studio",
    metaDescription: "Convert JSON objects into TypeScript interfaces instantly.",
    featured: true,
    popular: true,
    isNew: true,
    related: ["json-formatter", "regex-tester", "curl-to-fetch-converter"]
  },
  {
    slug: "curl-to-fetch-converter",
    name: "cURL to Fetch Converter",
    description: "Convert cURL commands to browser fetch and optional axios code.",
    category: "developer",
    route: "/tools/curl-to-fetch-converter",
    keywords: ["curl", "fetch", "axios", "http", "api"],
    title: "cURL to Fetch Converter | Altcore Tools Studio",
    metaDescription: "Convert cURL snippets into fetch() and axios-ready JavaScript.",
    featured: true,
    popular: true,
    isNew: true,
    related: ["json-formatter", "url-encoder-decoder", "json-to-typescript-generator"]
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps and readable dates with ISO support.",
    category: "developer",
    route: "/tools/timestamp-converter",
    keywords: ["timestamp", "unix", "date", "iso", "milliseconds"],
    title: "Timestamp Converter | Altcore Tools Studio",
    metaDescription: "Convert timestamp to date and date to timestamp with one click.",
    featured: true,
    popular: true,
    isNew: true,
    related: ["discord-timestamp-builder", "json-formatter", "curl-to-fetch-converter"]
  },
  {
    slug: "base64-encoder-decoder",
    name: "Base64 Encoder Decoder",
    description: "Encode and decode Base64 text with Unicode support.",
    category: "developer",
    route: "/tools/base64-encoder-decoder",
    keywords: ["base64", "encode", "decode", "utf-8"],
    title: "Base64 Encoder Decoder | Altcore Tools Studio",
    metaDescription: "Encode and decode Base64 strings with reliable browser-side processing.",
    featured: true,
    popular: true,
    related: ["url-encoder-decoder", "json-formatter"]
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder Decoder",
    description: "Encode or decode URL-safe text and query segments.",
    category: "utility",
    route: "/tools/url-encoder-decoder",
    keywords: ["url", "encode", "decode", "query"],
    title: "URL Encoder Decoder | Altcore Tools Studio",
    metaDescription: "Quick URL encode/decode for query params and safe links.",
    popular: true,
    related: ["base64-encoder-decoder", "text-case-converter"]
  },
  {
    slug: "jwt-decoder-inspector",
    name: "JWT Decoder Inspector",
    description: "Decode JWT header and payload locally with clear sections.",
    category: "developer",
    route: "/tools/jwt-decoder-inspector",
    keywords: ["jwt", "token", "decode", "auth"],
    title: "JWT Decoder Inspector | Altcore Tools Studio",
    metaDescription: "Inspect JWT claims locally. No signature verification and no server upload.",
    featured: true,
    popular: true,
    related: ["json-formatter", "regex-tester"]
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUID v4 and multiple IDs in one click.",
    category: "developer",
    route: "/tools/uuid-generator",
    keywords: ["uuid", "id", "random", "generator"],
    title: "UUID Generator | Altcore Tools Studio",
    metaDescription: "Generate one or multiple UUID v4 values quickly.",
    featured: false,
    popular: true,
    related: ["password-generator", "base64-encoder-decoder"]
  },
  {
    slug: "discord-embed-builder",
    name: "Discord Embed Builder",
    description: "Create full Discord embed JSON with a live visual preview.",
    category: "discord",
    route: "/tools/discord-embed-builder",
    keywords: ["discord", "embed", "webhook", "json", "bot"],
    title: "Discord Embed Builder | Altcore Tools Studio",
    metaDescription: "Build Discord embeds with title, author, footer, media and copy-ready JSON.",
    featured: true,
    popular: true,
    ogImage: "/og/discord-embed-builder.jpg",
    related: ["discord-timestamp-builder", "discord-username-generator", "discord-markdown-formatter"]
  },
  {
    slug: "discord-timestamp-builder",
    name: "Discord Timestamp Builder",
    description: "Generate all Discord timestamp formats like <t:...:R>.",
    category: "discord",
    route: "/tools/discord-timestamp-builder",
    keywords: ["discord", "timestamp", "time", "tag"],
    title: "Discord Timestamp Builder | Altcore Tools Studio",
    metaDescription: "Build Discord timestamps and copy each style instantly.",
    featured: true,
    popular: true,
    related: ["discord-embed-builder", "discord-markdown-formatter"]
  },
  {
    slug: "discord-username-generator",
    name: "Discord Username Generator",
    description: "Generate Discord usernames from style and keyword.",
    category: "discord",
    route: "/tools/discord-username-generator",
    keywords: ["discord", "username", "name", "generator"],
    title: "Discord Username Generator | Altcore Tools Studio",
    metaDescription: "Generate Discord username ideas by style with copy actions.",
    featured: true,
    popular: true,
    related: ["discord-embed-builder", "gamertag-generator"]
  },
  {
    slug: "discord-markdown-formatter",
    name: "Discord Markdown Formatter",
    description: "Build Discord markdown snippets (bold, quote, spoiler, code).",
    category: "discord",
    route: "/tools/discord-markdown-formatter",
    keywords: ["discord", "markdown", "format", "spoiler", "code"],
    title: "Discord Markdown Formatter | Altcore Tools Studio",
    metaDescription: "Generate ready-to-copy Discord markdown patterns and formats.",
    isNew: true,
    related: ["discord-embed-builder", "discord-timestamp-builder"]
  },
  {
    slug: "youtube-title-generator",
    name: "YouTube Title Generator",
    description: "Generate multiple YouTube title ideas from a topic.",
    category: "creator",
    route: "/tools/youtube-title-generator",
    keywords: ["youtube", "title", "creator", "seo"],
    title: "YouTube Title Generator | Altcore Tools Studio",
    metaDescription: "Generate cleaner, stronger YouTube title options quickly.",
    featured: true,
    popular: true,
    related: ["youtube-description-generator", "hashtag-generator", "thumbnail-text-analyzer"]
  },
  {
    slug: "youtube-description-generator",
    name: "YouTube Description Generator",
    description: "Create a structured video description with CTA and tags.",
    category: "creator",
    route: "/tools/youtube-description-generator",
    keywords: ["youtube", "description", "creator", "video"],
    title: "YouTube Description Generator | Altcore Tools Studio",
    metaDescription: "Generate polished YouTube descriptions from topic and tone.",
    isNew: true,
    related: ["youtube-title-generator", "hashtag-generator"]
  },
  {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Generate hashtags by topic and social platform.",
    category: "creator",
    route: "/tools/hashtag-generator",
    keywords: ["hashtags", "instagram", "youtube", "tiktok", "creator"],
    title: "Hashtag Generator | Altcore Tools Studio",
    metaDescription: "Generate targeted hashtags for YouTube, TikTok, Instagram and X.",
    isNew: true,
    related: ["youtube-title-generator", "youtube-description-generator"]
  },
  {
    slug: "gamertag-generator",
    name: "Gamertag Generator",
    description: "Generate style-based gamertag lists with copy actions.",
    category: "gaming",
    route: "/tools/gamertag-generator",
    keywords: ["gamertag", "gaming", "name", "generator"],
    title: "Gamertag Generator | Altcore Tools Studio",
    metaDescription: "Generate gamertags using keyword and tone presets.",
    featured: true,
    popular: true,
    ogImage: "/og/gamertag-generator.jpg",
    related: ["minecraft-name-generator", "clan-name-generator", "discord-username-generator"]
  },
  {
    slug: "minecraft-name-generator",
    name: "Minecraft Name Generator",
    description: "Generate Minecraft-safe names with 16-char compliance.",
    category: "gaming",
    route: "/tools/minecraft-name-generator",
    keywords: ["minecraft", "username", "name", "gaming"],
    title: "Minecraft Name Generator | Altcore Tools Studio",
    metaDescription: "Generate simple Minecraft-friendly names by style.",
    featured: true,
    popular: true,
    related: ["gamertag-generator", "clan-name-generator"]
  },
  {
    slug: "clan-name-generator",
    name: "Clan Name Generator",
    description: "Generate clan and team names by tone.",
    category: "gaming",
    route: "/tools/clan-name-generator",
    keywords: ["clan", "team", "esports", "name"],
    title: "Clan Name Generator | Altcore Tools Studio",
    metaDescription: "Generate multiple clan names for teams, guilds or communities.",
    isNew: true,
    related: ["gamertag-generator", "minecraft-name-generator"]
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text between lower, upper, title and sentence case.",
    category: "utility",
    route: "/tools/text-case-converter",
    keywords: ["text", "case", "uppercase", "lowercase"],
    title: "Text Case Converter | Altcore Tools Studio",
    metaDescription: "Convert text case instantly with one-click transforms.",
    popular: true,
    related: ["url-encoder-decoder", "lorem-ipsum-generator"]
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate paragraphs and words for design and content mocks.",
    category: "utility",
    route: "/tools/lorem-ipsum-generator",
    keywords: ["lorem ipsum", "placeholder", "text", "generator"],
    title: "Lorem Ipsum Generator | Altcore Tools Studio",
    metaDescription: "Generate customizable lorem ipsum text for prototypes.",
    related: ["text-case-converter"]
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with custom length and options.",
    category: "utility",
    route: "/tools/password-generator",
    keywords: ["password", "security", "generator", "random"],
    title: "Password Generator | Altcore Tools Studio",
    metaDescription: "Generate strong random passwords with symbol and number controls.",
    popular: true,
    related: ["uuid-generator"]
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate random color palettes for UI and brand exploration.",
    category: "utility",
    route: "/tools/color-palette-generator",
    keywords: ["color", "palette", "ui", "design"],
    title: "Color Palette Generator | Altcore Tools Studio",
    metaDescription: "Generate and copy random color palettes for projects.",
    isNew: true,
    related: ["color-palette-contrast-checker"]
  },
  {
    slug: "color-palette-contrast-checker",
    name: "Color Contrast Checker",
    description: "Check WCAG contrast ratio with AA/AAA indicators.",
    category: "utility",
    route: "/tools/color-palette-contrast-checker",
    keywords: ["contrast", "wcag", "aa", "aaa", "accessibility"],
    title: "Color Contrast Checker | Altcore Tools Studio",
    metaDescription: "Check text/background contrast ratio and WCAG pass level.",
    related: ["color-palette-generator"]
  },
  {
    slug: "thumbnail-text-analyzer",
    name: "Thumbnail Text Analyzer",
    description: "Evaluate thumbnail text length and readability score.",
    category: "creator",
    route: "/tools/thumbnail-text-analyzer",
    keywords: ["thumbnail", "youtube", "title", "seo"],
    title: "Thumbnail Text Analyzer | Altcore Tools Studio",
    metaDescription: "Analyze thumbnail text length, caps ratio and readability.",
    related: ["youtube-title-generator"]
  },
  {
    slug: "discord-poll-builder",
    name: "Discord Poll Builder",
    description: "Create clean Discord poll messages with emoji vote options.",
    category: "discord",
    route: "/tools/discord-poll-builder",
    keywords: ["discord", "poll", "vote", "community"],
    title: "Discord Poll Builder | Altcore Tools Studio",
    metaDescription: "Generate Discord poll text and vote options instantly.",
    isNew: true,
    related: ["discord-markdown-formatter", "discord-embed-builder"]
  },
  {
    slug: "discord-rules-generator",
    name: "Discord Rules Generator",
    description: "Generate server rules based on style and community focus.",
    category: "discord",
    route: "/tools/discord-rules-generator",
    keywords: ["discord", "rules", "server", "moderation"],
    title: "Discord Rules Generator | Altcore Tools Studio",
    metaDescription: "Generate structured Discord server rules quickly.",
    isNew: true,
    related: ["discord-poll-builder", "discord-embed-builder"]
  },
  {
    slug: "discord-channel-name-generator",
    name: "Discord Channel Name Generator",
    description: "Generate channel names by style and category purpose.",
    category: "discord",
    route: "/tools/discord-channel-name-generator",
    keywords: ["discord", "channel", "names", "server setup"],
    title: "Discord Channel Name Generator | Altcore Tools Studio",
    metaDescription: "Get Discord channel name ideas for community structure.",
    isNew: true,
    related: ["discord-rules-generator", "discord-username-generator"]
  },
  {
    slug: "clan-tag-generator",
    name: "Clan Tag Generator",
    description: "Generate short clan tags for FPS and team identity.",
    category: "gaming",
    route: "/tools/clan-tag-generator",
    keywords: ["clan", "tag", "gaming", "esports"],
    title: "Clan Tag Generator | Altcore Tools Studio",
    metaDescription: "Generate short and readable clan tags in seconds.",
    isNew: true,
    related: ["clan-name-generator", "gamertag-generator"]
  },
  {
    slug: "loadout-name-generator",
    name: "Loadout Name Generator",
    description: "Generate loadout names for weapon classes and play styles.",
    category: "gaming",
    route: "/tools/loadout-name-generator",
    keywords: ["loadout", "weapon", "gaming", "build names"],
    title: "Loadout Name Generator | Altcore Tools Studio",
    metaDescription: "Generate creative loadout names for your game builds.",
    isNew: true,
    related: ["clan-tag-generator", "gamertag-generator"]
  },
  {
    slug: "steam-bio-generator",
    name: "Steam Bio Generator",
    description: "Generate short Steam profile bios by tone.",
    category: "gaming",
    route: "/tools/steam-bio-generator",
    keywords: ["steam", "bio", "gaming profile", "about me"],
    title: "Steam Bio Generator | Altcore Tools Studio",
    metaDescription: "Generate Steam bio ideas for gamer profiles.",
    isNew: true,
    related: ["gamertag-generator", "minecraft-name-generator"]
  },
  {
    slug: "video-hook-generator",
    name: "Video Hook Generator",
    description: "Generate strong opening hooks for short or long videos.",
    category: "creator",
    route: "/tools/video-hook-generator",
    keywords: ["hook", "video", "creator", "retention"],
    title: "Video Hook Generator | Altcore Tools Studio",
    metaDescription: "Generate stronger video opening hooks for retention.",
    isNew: true,
    related: ["youtube-title-generator", "youtube-description-generator"]
  },
  {
    slug: "content-calendar-generator",
    name: "Content Calendar Generator",
    description: "Generate a weekly content plan by niche and format.",
    category: "creator",
    route: "/tools/content-calendar-generator",
    keywords: ["content calendar", "planning", "creator", "social"],
    title: "Content Calendar Generator | Altcore Tools Studio",
    metaDescription: "Generate a weekly creator content calendar instantly.",
    isNew: true,
    related: ["hashtag-generator", "youtube-title-generator"]
  },
  {
    slug: "social-caption-generator",
    name: "Social Caption Generator",
    description: "Generate social captions for posts, reels and clips.",
    category: "creator",
    route: "/tools/social-caption-generator",
    keywords: ["caption", "social media", "creator", "copywriting"],
    title: "Social Caption Generator | Altcore Tools Studio",
    metaDescription: "Generate post captions quickly by tone and platform.",
    isNew: true,
    related: ["hashtag-generator", "video-hook-generator"]
  },
  {
    slug: "discord-message-splitter",
    name: "Discord Message Splitter",
    description: "Split long text into Discord-safe 2000-char chunks.",
    category: "discord",
    route: "/tools/discord-message-splitter",
    keywords: ["discord", "split", "message", "2000 chars"],
    title: "Discord Message Splitter | Altcore Tools Studio",
    metaDescription: "Split long text for Discord character limits instantly.",
    isNew: true,
    related: ["discord-markdown-formatter", "discord-poll-builder"]
  },
  {
    slug: "discord-reaction-role-builder",
    name: "Discord Reaction Role Builder",
    description: "Generate reaction role messages with emoji-role mapping.",
    category: "discord",
    route: "/tools/discord-reaction-role-builder",
    keywords: ["discord", "reaction roles", "emoji", "roles"],
    title: "Discord Reaction Role Builder | Altcore Tools Studio",
    metaDescription: "Create structured reaction role messages for Discord servers.",
    isNew: true,
    related: ["discord-poll-builder", "discord-rules-generator"]
  },
  {
    slug: "discord-event-announcement-generator",
    name: "Discord Event Announcement Generator",
    description: "Generate event announcements with schedule and CTA.",
    category: "discord",
    route: "/tools/discord-event-announcement-generator",
    keywords: ["discord", "event", "announcement", "community"],
    title: "Discord Event Announcement Generator | Altcore Tools Studio",
    metaDescription: "Create cleaner event announcement posts for Discord communities.",
    isNew: true,
    related: ["discord-timestamp-builder", "discord-poll-builder"]
  },
  {
    slug: "discord-welcome-message-generator",
    name: "Discord Welcome Message Generator",
    description: "Generate onboarding welcome messages for new members.",
    category: "discord",
    route: "/tools/discord-welcome-message-generator",
    keywords: ["discord", "welcome", "onboarding", "server"],
    title: "Discord Welcome Message Generator | Altcore Tools Studio",
    metaDescription: "Generate welcome messages and first steps for new Discord members.",
    isNew: true,
    related: ["discord-rules-generator", "discord-channel-name-generator"]
  },
  {
    slug: "discord-server-idea-generator",
    name: "Discord Server Idea Generator",
    description: "Generate original server concepts with audience and themes.",
    category: "fun",
    route: "/tools/discord-server-idea-generator",
    keywords: ["discord", "server ideas", "community", "concept"],
    title: "Discord Server Idea Generator | Altcore Tools Studio",
    metaDescription: "Generate unique Discord server ideas in one click.",
    isNew: true,
    related: ["discord-channel-name-generator", "discord-rules-generator"]
  },
  {
    slug: "gamer-challenge-generator",
    name: "Gamer Challenge Generator",
    description: "Generate fun in-game challenges for content and streams.",
    category: "fun",
    route: "/tools/gamer-challenge-generator",
    keywords: ["gaming", "challenge", "stream", "content"],
    title: "Gamer Challenge Generator | Altcore Tools Studio",
    metaDescription: "Generate random gaming challenges for creators and squads.",
    isNew: true,
    related: ["loadout-name-generator", "clan-tag-generator"]
  },
  {
    slug: "crosshair-style-generator",
    name: "Crosshair Style Generator",
    description: "Generate crosshair style presets by playstyle intent.",
    category: "gaming",
    route: "/tools/crosshair-style-generator",
    keywords: ["crosshair", "fps", "gaming", "aim"],
    title: "Crosshair Style Generator | Altcore Tools Studio",
    metaDescription: "Generate crosshair style presets for different FPS playstyles.",
    isNew: true,
    related: ["loadout-name-generator", "gamer-challenge-generator"]
  },
  {
    slug: "quest-name-generator",
    name: "Quest Name Generator",
    description: "Generate fantasy quest titles and mission names.",
    category: "gaming",
    route: "/tools/quest-name-generator",
    keywords: ["quest", "rpg", "fantasy", "name generator"],
    title: "Quest Name Generator | Altcore Tools Studio",
    metaDescription: "Generate original quest names for RPG campaigns and games.",
    isNew: true,
    related: ["clan-name-generator", "clan-tag-generator"]
  },
  {
    slug: "speedrun-split-planner",
    name: "Speedrun Split Planner",
    description: "Plan split targets and pace per segment.",
    category: "gaming",
    route: "/tools/speedrun-split-planner",
    keywords: ["speedrun", "splits", "planner", "timing"],
    title: "Speedrun Split Planner | Altcore Tools Studio",
    metaDescription: "Plan and copy split targets for your speedrun attempts.",
    isNew: true,
    related: ["gamer-challenge-generator", "steam-bio-generator"]
  },
  {
    slug: "loot-drop-simulator",
    name: "Loot Drop Simulator",
    description: "Simulate drop chances and pity counters locally.",
    category: "fun",
    route: "/tools/loot-drop-simulator",
    keywords: ["loot", "drop rate", "rng", "simulator"],
    title: "Loot Drop Simulator | Altcore Tools Studio",
    metaDescription: "Run local drop-rate simulations to estimate expected outcomes.",
    isNew: true,
    related: ["gamer-challenge-generator", "speedrun-split-planner"]
  },
  {
    slug: "video-script-timer",
    name: "Video Script Timer",
    description: "Estimate speaking duration from script text length.",
    category: "creator",
    route: "/tools/video-script-timer",
    keywords: ["video script", "timer", "duration", "creator"],
    title: "Video Script Timer | Altcore Tools Studio",
    metaDescription: "Estimate voiceover duration and pacing from script text.",
    isNew: true,
    related: ["video-hook-generator", "youtube-description-generator"]
  },
  {
    slug: "carousel-outline-generator",
    name: "Carousel Outline Generator",
    description: "Generate slide-by-slide outline for social carousels.",
    category: "creator",
    route: "/tools/carousel-outline-generator",
    keywords: ["carousel", "slides", "outline", "content"],
    title: "Carousel Outline Generator | Altcore Tools Studio",
    metaDescription: "Generate social carousel outlines with hook, proof and CTA flow.",
    isNew: true,
    related: ["social-caption-generator", "content-calendar-generator"]
  },
  {
    slug: "hook-remix-lab",
    name: "Hook Remix Lab",
    description: "Remix one hook into multiple tonal variants.",
    category: "creator",
    route: "/tools/hook-remix-lab",
    keywords: ["hook", "copywriting", "creator", "variants"],
    title: "Hook Remix Lab | Altcore Tools Studio",
    metaDescription: "Generate multiple hook variations from one base sentence.",
    isNew: true,
    related: ["video-hook-generator", "social-caption-generator"]
  },
  {
    slug: "thumbnail-brief-generator",
    name: "Thumbnail Brief Generator",
    description: "Generate concise thumbnail design briefs from topic.",
    category: "creator",
    route: "/tools/thumbnail-brief-generator",
    keywords: ["thumbnail", "brief", "youtube", "design"],
    title: "Thumbnail Brief Generator | Altcore Tools Studio",
    metaDescription: "Generate thumbnail concept briefs with mood, text and focal subject.",
    isNew: true,
    related: ["thumbnail-text-analyzer", "youtube-title-generator"]
  },
  {
    slug: "content-angle-generator",
    name: "Content Angle Generator",
    description: "Generate unique framing angles for a given topic.",
    category: "creator",
    route: "/tools/content-angle-generator",
    keywords: ["content angle", "creator", "topic framing", "ideas"],
    title: "Content Angle Generator | Altcore Tools Studio",
    metaDescription: "Generate multiple fresh angles to avoid repetitive content.",
    isNew: true,
    related: ["video-hook-generator", "content-calendar-generator"]
  },
  {
    slug: "fake-profile-generator",
    name: "Fake Profile Generator",
    description: "Generate placeholder user profiles for UI testing.",
    category: "fun",
    route: "/tools/fake-profile-generator",
    keywords: ["fake data", "profile", "placeholder", "testing"],
    title: "Fake Profile Generator | Altcore Tools Studio",
    metaDescription: "Generate mock user profiles for prototypes and demos.",
    isNew: true,
    related: ["lorem-ipsum-generator", "uuid-generator"]
  },
  {
    slug: "text-glitch-generator",
    name: "Text Glitch Generator",
    description: "Generate stylized glitch text variants for social posts.",
    category: "fun",
    route: "/tools/text-glitch-generator",
    keywords: ["text glitch", "unicode", "style text", "generator"],
    title: "Text Glitch Generator | Altcore Tools Studio",
    metaDescription: "Generate glitch-styled text variants for captions and banners.",
    isNew: true,
    related: ["text-case-converter", "social-caption-generator"]
  },
  {
    slug: "pomodoro-session-planner",
    name: "Pomodoro Session Planner",
    description: "Generate focused work/break session plans from task list.",
    category: "utility",
    route: "/tools/pomodoro-session-planner",
    keywords: ["pomodoro", "focus", "planner", "productivity"],
    title: "Pomodoro Session Planner | Altcore Tools Studio",
    metaDescription: "Plan pomodoro cycles from your tasks and available time.",
    isNew: true,
    related: ["content-calendar-generator", "video-script-timer"]
  },
  {
    slug: "idea-combinator",
    name: "Idea Combinator",
    description: "Combine themes, audiences and formats into original concepts.",
    category: "fun",
    route: "/tools/idea-combinator",
    keywords: ["ideas", "brainstorm", "combination", "generator"],
    title: "Idea Combinator | Altcore Tools Studio",
    metaDescription: "Generate new project ideas by combining random concept blocks.",
    isNew: true,
    related: ["content-angle-generator", "discord-server-idea-generator"]
  },
  {
    slug: "random-wheel-picker",
    name: "Random Wheel Picker",
    description: "Pick a random option from your custom list.",
    category: "fun",
    route: "/tools/random-wheel-picker",
    keywords: ["random", "picker", "wheel", "choice"],
    title: "Random Wheel Picker | Altcore Tools Studio",
    metaDescription: "Use a random picker for decisions, games or challenge selection.",
    isNew: true,
    related: ["gamer-challenge-generator", "idea-combinator"]
  },
  {
    slug: "discord-bot-template-basic",
    name: "Discord Bot Template Basic",
    description: "Copy-paste a minimal Discord bot starter template.",
    category: "discord",
    route: "/tools/discord-bot-template-basic",
    keywords: ["discord", "bot", "template", "starter", "discord.js"],
    title: "Discord Bot Template Basic | Altcore Tools Studio",
    metaDescription: "Get a minimal Discord bot template ready to copy and run.",
    isNew: true,
    related: ["discord-embed-builder", "discord-message-splitter", "discord-reaction-role-builder"]
  },
  {
    slug: "unity-csharp-script-generator",
    name: "Unity C# Script Generator",
    description: "Generate MonoBehaviour script templates with common methods.",
    category: "unity",
    route: "/tools/unity-csharp-script-generator",
    keywords: ["unity", "c#", "script", "monobehaviour", "template"],
    title: "Unity C# Script Generator | Altcore Tools Studio",
    metaDescription: "Generate Unity MonoBehaviour templates quickly for new scripts.",
    isNew: true,
    related: ["unity-fps-controller-script-generator", "unity-playerprefs-snippet-generator", "unity-tags-enum-generator"]
  },
  {
    slug: "unity-fps-controller-script-generator",
    name: "Unity FPS Controller Script Generator",
    description: "Generate a player controller script with movement and camera look.",
    category: "unity",
    route: "/tools/unity-fps-controller-script-generator",
    keywords: ["unity", "fps controller", "player movement", "camera", "c#"],
    title: "Unity FPS Controller Script Generator | Altcore Tools Studio",
    metaDescription: "Generate a ready-to-use Unity C# FPS controller script with mouse look.",
    isNew: true,
    popular: true,
    related: ["unity-csharp-script-generator", "unity-layermask-calculator", "unity-playerprefs-snippet-generator"]
  },
  {
    slug: "unity-playerprefs-snippet-generator",
    name: "Unity PlayerPrefs Snippet Generator",
    description: "Generate typed save/load snippets for PlayerPrefs keys.",
    category: "unity",
    route: "/tools/unity-playerprefs-snippet-generator",
    keywords: ["unity", "playerprefs", "save", "load", "c#"],
    title: "Unity PlayerPrefs Snippet Generator | Altcore Tools Studio",
    metaDescription: "Generate PlayerPrefs C# code snippets for int, float and string.",
    isNew: true,
    related: ["unity-csharp-script-generator", "unity-layermask-calculator"]
  },
  {
    slug: "unity-color-converter",
    name: "Unity Color Converter",
    description: "Convert HEX colors to Unity Color and Color32 snippets.",
    category: "unity",
    route: "/tools/unity-color-converter",
    keywords: ["unity", "color", "color32", "hex", "ui"],
    title: "Unity Color Converter | Altcore Tools Studio",
    metaDescription: "Convert hex values into Unity C# Color and Color32 code.",
    isNew: true,
    related: ["color-palette-generator", "unity-csharp-script-generator"]
  },
  {
    slug: "unity-layermask-calculator",
    name: "Unity LayerMask Calculator",
    description: "Compute LayerMask integer values from selected layer indices.",
    category: "unity",
    route: "/tools/unity-layermask-calculator",
    keywords: ["unity", "layermask", "layers", "physics", "raycast"],
    title: "Unity LayerMask Calculator | Altcore Tools Studio",
    metaDescription: "Calculate Unity LayerMask bit values for raycasts and collisions.",
    isNew: true,
    related: ["unity-playerprefs-snippet-generator", "unity-tags-enum-generator"]
  },
  {
    slug: "unity-tags-enum-generator",
    name: "Unity Tags Enum Generator",
    description: "Generate C# enum and constants from your tags/layers list.",
    category: "unity",
    route: "/tools/unity-tags-enum-generator",
    keywords: ["unity", "tags", "enum", "constants", "c#"],
    title: "Unity Tags Enum Generator | Altcore Tools Studio",
    metaDescription: "Generate typed C# enums/constants from Unity tag names.",
    isNew: true,
    related: ["unity-csharp-script-generator", "unity-layermask-calculator"]
  },
  {
    slug: "unity-bezier-path-sampler",
    name: "Unity Bezier Path Sampler",
    description: "Sample cubic Bezier points and export a Unity Vector3 path.",
    category: "unity",
    route: "/tools/unity-bezier-path-sampler",
    keywords: ["unity", "bezier", "path", "vector3", "spline"],
    title: "Unity Bezier Path Sampler | Altcore Tools Studio",
    metaDescription: "Generate sampled Vector3 paths from cubic Bezier control points.",
    isNew: true,
    related: ["unity-vector3-parser", "unity-navmesh-patrol-generator"]
  },
  {
    slug: "unity-quaternion-euler-helper",
    name: "Unity Quaternion Euler Helper",
    description: "Convert Euler angles into Quaternion usage snippets.",
    category: "unity",
    route: "/tools/unity-quaternion-euler-helper",
    keywords: ["unity", "quaternion", "euler", "rotation", "math"],
    title: "Unity Quaternion Euler Helper | Altcore Tools Studio",
    metaDescription: "Convert Euler values to Quaternion-ready Unity code snippets.",
    isNew: true,
    related: ["unity-fps-controller-script-generator", "unity-csharp-script-generator"]
  },
  {
    slug: "unity-vector3-parser",
    name: "Unity Vector3 Parser",
    description: "Parse raw XYZ lines into Vector3 arrays and center point.",
    category: "unity",
    route: "/tools/unity-vector3-parser",
    keywords: ["unity", "vector3", "coordinates", "parser"],
    title: "Unity Vector3 Parser | Altcore Tools Studio",
    metaDescription: "Convert coordinate text into Vector3[] snippets for Unity.",
    isNew: true,
    related: ["unity-bezier-path-sampler", "unity-layermask-calculator"]
  },
  {
    slug: "unity-animationcurve-preset-generator",
    name: "Unity AnimationCurve Preset Generator",
    description: "Generate reusable AnimationCurve code presets.",
    category: "unity",
    route: "/tools/unity-animationcurve-preset-generator",
    keywords: ["unity", "animationcurve", "keyframe", "preset", "easing"],
    title: "Unity AnimationCurve Preset Generator | Altcore Tools Studio",
    metaDescription: "Generate AnimationCurve presets for movement, UI and effects timing.",
    isNew: true,
    related: ["unity-scriptableobject-template-generator", "unity-csharp-script-generator"]
  },
  {
    slug: "unity-shader-keyword-helper",
    name: "Unity Shader Keyword Helper",
    description: "Generate shader keyword declarations and C# toggle snippets.",
    category: "unity",
    route: "/tools/unity-shader-keyword-helper",
    keywords: ["unity", "shader", "keyword", "material", "render"],
    title: "Unity Shader Keyword Helper | Altcore Tools Studio",
    metaDescription: "Build shader keyword pragma lines and runtime C# enable/disable code.",
    isNew: true,
    related: ["unity-color-converter", "unity-csharp-script-generator"]
  },
  {
    slug: "unity-scriptableobject-template-generator",
    name: "Unity ScriptableObject Template Generator",
    description: "Generate ScriptableObject templates from typed field lines.",
    category: "unity",
    route: "/tools/unity-scriptableobject-template-generator",
    keywords: ["unity", "scriptableobject", "template", "data", "c#"],
    title: "Unity ScriptableObject Template Generator | Altcore Tools Studio",
    metaDescription: "Generate ScriptableObject class templates with serialized fields.",
    isNew: true,
    related: ["unity-csharp-script-generator", "unity-animationcurve-preset-generator"]
  },
  {
    slug: "unity-object-pool-planner",
    name: "Unity Object Pool Planner",
    description: "Estimate object pool size from spawn rate and lifetime.",
    category: "unity",
    route: "/tools/unity-object-pool-planner",
    keywords: ["unity", "object pooling", "performance", "spawn", "memory"],
    title: "Unity Object Pool Planner | Altcore Tools Studio",
    metaDescription: "Estimate recommended initial pool size for spawned gameplay objects.",
    isNew: true,
    popular: true,
    related: ["unity-fps-controller-script-generator", "unity-csharp-script-generator"]
  },
  {
    slug: "unity-navmesh-patrol-generator",
    name: "Unity NavMesh Patrol Generator",
    description: "Generate a NavMesh waypoint patrol script skeleton.",
    category: "unity",
    route: "/tools/unity-navmesh-patrol-generator",
    keywords: ["unity", "navmesh", "ai", "patrol", "agent"],
    title: "Unity NavMesh Patrol Generator | Altcore Tools Studio",
    metaDescription: "Generate a patrol AI skeleton using NavMeshAgent and waypoint transforms.",
    isNew: true,
    related: ["unity-bezier-path-sampler", "unity-fps-controller-script-generator"]
  },
  {
    slug: "unity-layer-collision-matrix-helper",
    name: "Unity Layer Collision Matrix Helper",
    description: "Generate Physics.IgnoreLayerCollision calls from layer pairs.",
    category: "unity",
    route: "/tools/unity-layer-collision-matrix-helper",
    keywords: ["unity", "layer collision", "physics", "matrix", "ignore"],
    title: "Unity Layer Collision Matrix Helper | Altcore Tools Studio",
    metaDescription: "Generate runtime layer collision ignore snippets for Unity physics.",
    isNew: true,
    related: ["unity-layermask-calculator", "unity-playerprefs-snippet-generator"]
  },
  {
    slug: "unity-assembly-definition-generator",
    name: "Unity Assembly Definition Generator",
    description: "Generate .asmdef JSON with references and platform mode.",
    category: "unity",
    route: "/tools/unity-assembly-definition-generator",
    keywords: ["unity", "asmdef", "assembly definition", "compilation"],
    title: "Unity Assembly Definition Generator | Altcore Tools Studio",
    metaDescription: "Generate clean .asmdef files for runtime or editor assemblies.",
    isNew: true,
    related: ["unity-csharp-script-generator", "unity-scriptableobject-template-generator"]
  }
];

export const getToolBySlug = (slug?: string) => toolsConfig.find((tool) => tool.slug === slug);

export const getToolByRoute = (route: string) => toolsConfig.find((tool) => tool.route === route);

export const getRelatedTools = (slug: string) => {
  const current = getToolBySlug(slug);
  if (!current) return [];
  if (current.related?.length) {
    return current.related.map((s) => getToolBySlug(s)).filter(Boolean) as ToolConfig[];
  }
  return toolsConfig.filter((tool) => tool.category === current.category && tool.slug !== slug).slice(0, 3);
};
